DEV = False
DEFAULT_LINK_TO_PARSE = 'https://sp10050fd0.guided.ss-omtrdc.net/?do=json&count=100&i=0&x1=featured_id&q1=hardToFindFlag%7CexclusiveFlag&showRetired=true&cc=it&lang=it'
DEFAULT_COLLECTION_TO_SAVE_TO = 'exclusive_set'
MONGO_SECRET_FILE = './grant/mongo_secret.txt'
MONGODB_HOST = 'localhost'#'46.101.220.66'
MONGO_PORT = 27017
MAIN_DB = 'lego_price_monitor'
MAIL_SECRET_FILE = './grant/mail_secret.txt'
MAIL_RECEIVERS = ['diblasi.davide@gmail.com','raoulsanfratello@hotmail.it']
